### PR TITLE
Python 2 to Python 3

### PR DESCRIPTION
**Pull request by sharanp98**
As Python 3 is the present and the future, the codebase has been converted entirely from Python 2 to 3. Care has been taken to not just add parentheses for the print statements but also other differences between the two Python versions have been dealt with and tested. 
Note: The **annotation tool** had some dependency issues and has **not been** changed to Python 3.
An additional feature added was the user can pass as **input a folder** that contains image files to annotate instead of passing individual image files.

### CODE REVIEW

**Comment by Lyyyyyyy** [comment]
Scanning /home/lyy/PycharmProjects/alpr-unconstrained-py3/samples/test/03009.JPG
		0 cars found
	Scanning /home/lyy/PycharmProjects/alpr-unconstrained-py3/samples/test/03016.jpg
		0 cars found
	Scanning /home/lyy/PycharmProjects/alpr-unconstrained-py3/samples/test/03025.jpg
		0 cars found


Under python3, I don't know why I can't locate the vehicle. It runs normally under python2. Have you ever had this situation?

**Comment by sharanp98** [comment]
> Scanning /home/lyy/PycharmProjects/alpr-unconstrained-py3/samples/test/03009.JPG
> 0 cars found
> Scanning /home/lyy/PycharmProjects/alpr-unconstrained-py3/samples/test/03016.jpg
> 0 cars found
> Scanning /home/lyy/PycharmProjects/alpr-unconstrained-py3/samples/test/03025.jpg
> 0 cars found
> 
> Under python3, I don't know why I can't locate the vehicle. It runs normally under python2. Have you ever had this situation?

Yes, I had the same issue as well. I am working on the solution. Meanwhile, if you approach a solution, please open a PR

**Comment by brunomossmann** [comment]
You need to decode the string in the following line of code under detect() function in darknet.py and you should be fine:
res.append((meta.names[i].decode("utf-8"), dets[j].prob[i], (b.x, b.y, b.w, b.h)))

**Comment by kurzacz** [comment]
I was getting following error:

> File "vehicle-detection.py", line 53, in <module>
>     Iorig = cv2.imread(img_path)
> TypeError: bad argument type for built-in operation

Reason: `img_path` argument passed as bytes string.

Fixed with changing vehicle-detection.py line 53:
from: `Iorig = cv2.imread(img_path)`
to: `Iorig = cv2.imread(img_path.decode('utf-8'))`

**Comment by Frank-qlu** [comment]
mask_scale: Using default '1.000000' Loading weights from data/ocr/ocr-net.weights...Done! Performing OCR... rm: cannot remove '/tmp/output/*_lp.png': No such file or directory #100
           when i use the train code,i change run.py p_model="models/my-trained-model/my-trained-model_final.h5"
it has some problems ,
"mask_scale: Using default '1.000000'
Loading weights from data/ocr/ocr-net.weights...Done!
Performing OCR...
rm: cannot remove '/tmp/output/*_lp.png': No such file or directory
"
how can i solve it ,thank you very much

**Comment by choobs96** [comment]
To train the model. 
The issue with train_detector.py. 
Couldn't calculate model_stide due to int/dimension type.
I've added int in front of the output_shape[1] and it works.
Let me know if this is the right way.
-----------------------------------------------------------------------------
def load_network(modelpath,input_dim):

	model = load_model(modelpath)
	input_shape = (input_dim,input_dim,3)

	# Fixed input size for training
	inputs  = keras.layers.Input(shape=(input_dim,input_dim,3))
	outputs = model(inputs)

	output_shape = tuple([s for s in outputs.shape[1:]])
	output_dim   = int(output_shape[1])
	model_stride = input_dim / output_dim
	

	assert input_dim % int(output_dim) == 0, \
		'The output resolution must be divisible by the input resolution'

	assert model_stride == 2**4, \
		'Make sure your model generates a feature map with resolution ' \
		'16x smaller than the input'

Thanks! :)

**Comment by yazeedhasan97** [comment]
Hi @sharanp98,

How can we download or pull your commits

**Comment by yazeedhasan97** [comment]
boss, please help us make use of your implementation

**Comment by sharanp98** [comment]
> boss, please help us make use of your implementation

Hi, I am longer working on this project and hence deleted the repo. There were other issues as well. Sorry about that, hope you can find a better repo

**Pull request closed without merging**
